### ISSUE TITLE
Improve MapStore theme

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#6986]
## Description

We should improve the theme and separate as much as possible the CSS classes that represent the structure (something that usually never change eg: positioning, layout) to the one that represent the theme (eg: colors, fonts family) in this way we could create a separate compact .less/css file with only the classes related to theming. If we introduce also the [CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) to change the primary colors this will allow a more dynamic update of the theme.

Expcted styles output

- default.css (compiled from)
  - @import "base.less";
  - @import "icons.less";
  - @import "bootstrap-theme.less";
  - @import "ms-structure.less"; // split ms2-theme.less only structure part
  - @import "ms-theme.less"; // split ms2-theme.less only theming part
  - @import "variables.less";
- custom-theme.css (compiled from)
  - @import "ms-theme.less";
  - @import "variables.less"; // my theme variables
 
If it's not possible to keep a complete separation between structure and theme we should at least make that clear inside the less files with proper indication of the various parts.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Other... Please describe: Theme improvement

### About CSS custom properties

This is the expected structure of classes to ensure a complete support with fallback:

- less
```less
@ms-primary-bg: #ff33aa;
.my-class {
  // this could be a mixin
  background-color: @ms-primary-bg;
  background-color: var(--ms-primary-bg, @ms-primary-bg);
}
```

- compiled css
```css
.my-class {
  background-color: #ff33aa; /* fallback color if var() is not supported in the browser */
  background-color: var(--ms-primary-bg, #ff33aa);
}
```

it's possible to override the value of `--ms-primary-bg` by adding a style tag in the html page after the theme link declaration
```html
<style>
  :root {
    --ms-primary-bg: #ff0000; /* change bg of my-class to red */
  }
</style>
```
