### ISSUE TITLE
FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by franklintiel** [geosolutions-it/MapStore2#9040]
## Description
Hi everyone, I hope you can help me, we have problem from some days ago.
I have a container to start Mapstore, Postgres and Pgadmin, this was working good but the postgres fails now.

I have the following structure:

```
- root project
- docker-compose.mapstore.yml
- mapstore/
- - Dockerfile
- - geostore-datasource-ovr-postgres.properties
- - mapstore.conf
- - wait-for-postgres.sh
- - postgres/
- - - .env
- - - 01-init-user.sh
- - - Dockerfile
```

docker-compose.mapstore.yml:

```
version: "3.3"


services:
  postgis:
    restart: on-failure
    build:
      context: ./mapstore/postgres
    image: geosolutions-mapstore/postgis
    container_name: local-mapstore-postgis
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    env_file: 
      ./mapstore/postgres/.env
    volumes:
      - postgis_data:${PGDATA:-/var/lib/postgresql/data}:rw
    ports:
      - 5432:5432
  pgadmin:
    restart: always
    container_name: local-pgadmin
    build: 
      context: ./pgadmin
      dockerfile: Dockerfile
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - 4001:80
    env_file: 
      ./pgadmin/.env
    depends_on:
      - postgis
  mapstore:
    container_name: local-mapstore
    build:
      context: ./mapstore
      dockerfile: Dockerfile
      args:
        OVR: "geostore-datasource-ovr.properties"
        MAPSTORE_WEBAPP_SRC: "https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
    command: ["wait-for-postgres", "postgis", "5432", "postgres", "postgres", "catalina.sh", "run"]
    depends_on:
      - postgis
    ports:
      - 8080
  mapstore_nginx:
    image: nginx
    container_name: local-mapstore-nginx
    volumes:
      - ./mapstore/mapstore.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 4004:4007
    depends_on:
      - mapstore
      
volumes: 
  pgadmin_data:
    external: true
  postgis_data:
    external: true

```
geostore-datasource-ovr-postgres.properties:
```
#Default Postgres Connection values, uncomment for using postgres 
geostoreDataSource.driverClassName=org.postgresql.Driver
geostoreDataSource.url=jdbc:postgresql://postgis:5432/geostore
geostoreDataSource.username=geostore
geostoreDataSource.password=geostore
geostoreVendorAdapter.databasePlatform=org.hibernate.dialect.PostgreSQLDialect
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=validate
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]=geostore
geostoreVendorAdapter.generateDdl=true
geostoreVendorAdapter.showSql=false

```

wait-for-postgres.sh
```
#!/bin/bash
# wait-for-postgres.sh

set -e

host="$1"
shift
port="$1"
shift
user="$1"
shift
password="$1"
shift
cmd="$@"

export PGPASSWORD="$password"

set -x
until psql -h "$host" -p "$port" -U "$user"  -c '\l'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"
exec $cmd

```

.env
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=geostore
```
01-init-user.sh
```
#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname geostore <<-EOSQL
    CREATE user geostore LOGIN PASSWORD 'geostore' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
    CREATE SCHEMA geostore;
    GRANT USAGE ON SCHEMA geostore TO geostore ;
    GRANT ALL ON SCHEMA geostore TO geostore ;
    alter user geostore set search_path to geostore , public;
    CREATE user geostore_test LOGIN PASSWORD 'geostore_test' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
    CREATE SCHEMA geostore_test;
    GRANT USAGE ON SCHEMA geostore_test TO geostore_test;
    GRANT ALL ON SCHEMA geostore_test TO geostore_test;
    alter user geostore_test set search_path to geostore_test, public;
EOSQL

PGPASSWORD="geostore" PGOPTIONS="--search_path=geostore" psql -v ON_ERROR_STOP=1 --username geostore --dbname geostore < /code/002_create_schema_postgres.sql

```
Dockerfile inside postgres folder:

```
FROM postgis/postgis:12-3.1
WORKDIR /code
COPY ./01-init-user.sh /docker-entrypoint-initdb.d/
RUN apt-get update \
    && apt-get install wget -y \
    && rm -rf /var/cache/apt/*
RUN wget https://raw.githubusercontent.com/geosolutions-it/geostore/master/doc/sql/002_create_schema_postgres.sql

```

Dockerfile inside mapstore folder:
```
FROM tomcat:9-jdk11-openjdk AS mother
LABEL maintainer="Alessandro Parma<alessandro.parma@geosolutionsgroup.com>"
ARG MAPSTORE_WEBAPP_SRC="https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
ADD "${MAPSTORE_WEBAPP_SRC}" "/mapstore/"

COPY ./* /mapstore/docker/

RUN ls -l /mapstore/docker/


WORKDIR /mapstore

FROM tomcat:9-jdk11-openjdk

ENV CATALINA_BASE "$CATALINA_HOME"
ENV MAPSTORE_WEBAPP_DST="${CATALINA_BASE}/webapps"
ENV INITIAL_MEMORY="512m"
ENV MAXIMUM_MEMORY="512m"
ENV JAVA_OPTS="${JAVA_OPTS} -Xms${INITIAL_MEMORY} -Xmx${MAXIMUM_MEMORY}"

ARG OVR="geostore-datasource-ovr.properties"
ENV GEOSTORE_OVR_OPT="-Dgeostore-ovr=file://${CATALINA_BASE}/conf/${OVR}"
ARG DATA_DIR="${CATALINA_BASE}/datadir"
# ENV GEOSTORE_OVR_OPT=""
ENV JAVA_OPTS="${JAVA_OPTS} ${GEOSTORE_OVR_OPT} -Ddatadir.location=${DATA_DIR}"
ENV TERM xterm

COPY --from=mother "/mapstore/docker/geostore-datasource-ovr-postgres.properties" "${CATALINA_BASE}/conf/geostore-datasource-ovr.properties"

COPY --from=mother "/mapstore/mapstore.war" "${MAPSTORE_WEBAPP_DST}/mapstore.war"
COPY --from=mother "/mapstore/docker" "${CATALINA_BASE}/docker/"

RUN mkdir -p ${DATA_DIR}

RUN cp ${CATALINA_BASE}/docker/wait-for-postgres.sh /usr/bin/wait-for-postgres

RUN ls -l ${CATALINA_BASE}/conf

RUN apt-get update \
    && apt-get install --yes postgresql-client \
    && apt-get clean \
    && apt-get autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/man/* \
    && rm -rf /usr/share/doc/*

WORKDIR ${CATALINA_BASE}

VOLUME [ "${DATA_DIR}" ]

EXPOSE 8080

```

The files are similar to the base configurations recommended by the dev team from Mapstore, the two changes applied is the name assigned to the image related with the postgis database inside docker compose file and the copy applied from the postgres connection in the Dockerfile to start a Tomcat image.

## How to reproduce
- I run the following command:

```
docker compose -f docker-compose.mapstore.yml down && docker compose -f docker-compose.mapstore.yml up -d --build
```
 
*Current Result*

- The dockers display all running correctly:

```
IMAGE                           COMMAND                  CREATED         STATUS                   PORTS                            NAMES
nginx                           "/docker-entrypoint.…"   8 seconds ago   Up 7 seconds             80/tcp, 0.0.0.0:4004->4007/tcp   local-mapstore-nginx
sucre-mapstore                  "wait-for-postgres p…"   8 seconds ago   Up 8 seconds             0.0.0.0:49784->8080/tcp          local-mapstore
sucre-pgadmin                   "/entrypoint.sh"         8 seconds ago   Up 8 seconds             443/tcp, 0.0.0.0:4001->80/tcp    local-pgadmin
geosolutions-mapstore/postgis   "docker-entrypoint.s…"   8 seconds ago   Up 8 seconds (healthy)   0.0.0.0:5432->5432/tcp           local-mapstore-postgis
``` 
- I opened my browser display "502 Bad Gateway"

- I did access inside container to check if the war file was copied in the webapps folder from Tomcat and this was copied correctly:
```
$ docker exec -it sucre-mapstore sh
# pwd 
/usr/local/tomcat
# ls -l webapps
total 90316
-rw------- 1 root root 92480442 Mar  7 17:04 mapstore.war
```

- I see my logs from containers:
```
docker compose -f docker-compose.mapstore.yml logs -f
```

- I can see a loop with many messages with the same  output:
```
local-mapstore-postgis  | 2023-03-18 06:45:42.403 UTC [564] FATAL:  password authentication failed for user "postgres"
local-mapstore-postgis  | 2023-03-18 06:45:42.403 UTC [564] DETAIL:  Role "postgres" does not exist.
local-mapstore-postgis  | 	Connection matched pg_hba.conf line 99: "host all all all md5"
local-mapstore          | psql: error: FATAL:  password authentication failed for user "postgres"
local-mapstore          | + echo 'Postgres is unavailable - sleeping'
local-mapstore          | Postgres is unavailable - sleeping
local-mapstore          | + sleep 1
```
*Expected Result*

The process must run without problems but this not working, I don't know what happening, the structure is the same from the documentation, but this not working anymore, this was working correctly for weeks, but, this not working now,  I hope you can help me with it.

Thank you for your helps.

Best regards.
