### ISSUE TITLE
Re-enable PDF generation

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#9383]
## Description

Because of changes reported in #9369 , we needed to temorary disable PDF generation. With #9373 we have a version of the PDF that works (videos are not included). 

Anyway:
- the lib is quite old and not maintained
- it takes 500seconds to build
- Some issues (blank page at the beginning to solve) as well as update to latest mkdocs material

We have an alternative using `with-pdf` lib: 
- 90s to build
- Table of contents
- Better layout
- Possibility of several customizations

It's configuration have to be added in mkdocs.yml file, with the following output.

```
plugins:
  - search
  - with-pdf:
      #author: WHO
      copyright: GeoSolutionsGroup
      #
      #cover: false
      #back_cover: true
      cover_title: MapStore Documentation
      cover_subtitle: User Guide and Developer Guide
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      exclude_pages:
      #    - 'user-guide/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      # render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: pdf/mapstore_documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      show_anchors: true
      #verbose: true
```

We have to evaluate
-  if using this new lib or the old lib fixing the issues (evaluating quality of pdf and work to do)
- adding the proper link
- re-enable the PDF generation in readthedocs.io. (project settings, setting `ENABLE_PDF_EXPORT=1`, now is set to `0` due to the bad quality of the PDF generated)
